name = "digital-menu"
compatibility_date = "2024-11-01"
pages_build_output_dir = ".output"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "digital-menu-db"
database_id = "aa51aeaa-ff7f-4937-a1d5-d496394130d3"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "digital-menu-assets"
